

#' Save new cleaned seesion data joined with cleaned user_train
#'
#' @param cleaned_user cleaned training data, recommend load cleaned_train.RData
#' @param cleaned_session cleaned session data, recommend load cleaned_session.RData
get_train_session <- function(cleaned_user, cleaned_session) {
  user_session_train <- cleaned_user %>% left_join(cleaned_session, by = c("id" = "user_id"))
  # Fill NA after join, since there is no session data for the NA ones, we will just make them 0
  cleaned_session[,20:34]  <- cleaned_session[,20:34] %>% mutate(across(everything(), ~replace_na(.x, 0)))
  save(user_session_train, user_session_test, cleaned_session, file = "clean_session.RData")
}

#' Plot side-by-side box plot 
#'
#' @param train the dataframe with first column country_destination, which is the categorical response 
#'
#' @return a side-by-side boxplot of each column vs country_destination; generated by ggarrange
plot_sbs_box <- function(train) {
  train <- train %>% relocate(country_destination, .before = 1)
  ncol_train <- ncol(train)
  col_name_train <- colnames(train)
  test <- map(as.list(2:ncol_train), .f = function(col) {
    box <-   ggplot(data = train, aes(x = country_destination, y = train[, col], colour = country_destination)) +
      geom_boxplot(show.legend = FALSE) + ylab(col_name_train[col]) + xlab("")
    return(box)
  })
  
  eda_sbs_box <- ggpubr::ggarrange(plotlist = test)
  eda_sbs_box 
}
