---
title: "RandomForest"
---
File description:
- Perform Random Forest Model Training and Fitting for 4 submodels
  - Full model
  - Subseted model through Recursive Feature Selection
  - Undersampling model
  - Oversampling model
- Calculated roc and interval score values for the best model

# Load Data and Library
```{r Load Data}
load(paste0(here::here(), "/Data/airbnb_cleaned.RData"))
source("helper_function.R")
source("modeling_functions.R")
set.seed(2023)

library(purrr)
library(tidyverse)
library(caret)
library(randomForest)
library(pROC)

airbnb_data <- airbnb_cleaned
rm(airbnb_cleaned)
```

```{r Examine RFE results }
# source code to run recursive feature elimination for each training fold
# for (k in 1:5){
#   train_folds <- airbnb_cleaned[-folds[[k]], ]
#   res <- rfe_rf_procedure(train_folds)
#   save(res, file = paste0(here::here(), '/Data/rfe_',k, '.Rdata'))
# }

# Load the RFE results from each folds 
res_rfe_sub_1 <- loadRData(paste0(here::here(), '/Data/rfe_1.Rdata'))
res_rfe_sub_2 <- loadRData(paste0(here::here(), '/Data/rfe_2.Rdata'))
res_rfe_sub_3 <- loadRData(paste0(here::here(), '/Data/rfe_3.Rdata'))
res_rfe_sub_4 <- loadRData(paste0(here::here(), '/Data/rfe_4.Rdata'))
res_rfe_sub_5 <- loadRData(paste0(here::here(), '/Data/rfe_5.Rdata'))

# check what would be the best number of variables 
# by plot
plot(res_rfe_sub_1, type = c('g','o'), main="Fold 2-5")
plot(res_rfe_sub_2, type = c('g','o'), main="Fold 1 and 3-5")
plot(res_rfe_sub_3, type = c('g','o'), main="Fold 1-2 and 4-5")
plot(res_rfe_sub_4, type = c('g','o'), main="Fold 1-3 and 5")
plot(res_rfe_sub_5, type = c('g','o'), main="Fold 1-4")

# by number 
res_rfe_sub_1$bestSubset
res_rfe_sub_2$bestSubset
res_rfe_sub_3$bestSubset
res_rfe_sub_4$bestSubset
res_rfe_sub_5$bestSubset

```

```{r Check top5 most important variable}
res_rfe_sub_1$optVariables[1:5]
res_rfe_sub_2$optVariables[1:5]
res_rfe_sub_3$optVariables[1:5]
res_rfe_sub_4$optVariables[1:5]
res_rfe_sub_5$optVariables[1:5]
```


```{r}
# Each model take about 30 mins to run, 2 hr to run the whole thing
rf_full_result <- rf_5fold_cross(airbnb_data, folds, type ="full")

#' From rfe it is found that models with 19 variables are deemed to be the best subsetted model
#' This is just the same thing as the full model
rf_sub_result <- rf_full_result

rf_over_full_result <- rf_5fold_cross(airbnb_data, folds, type ="over")
rf_under_full_result <- rf_5fold_cross(airbnb_data, folds, type ="under")
```


```{r Get Misclassification Rate}
# load(paste0(here::here(), "/Data/rf_model_objects.RData"))
mis_class_sub <- extract_list_item(rf_sub_result, "mis_class")
mis_class_ful <- extract_list_item(rf_full_result, "mis_class")
mis_class_ful_under <- extract_list_item(rf_under_full_result, "mis_class")
mis_class_ful_over <- extract_list_item(rf_over_full_result, "mis_class")

rf_misclass <- data.frame(full_50 = sapply(mis_class_ful, "[", "pred50") %>% unlist(),
                          sub_50 = sapply(mis_class_sub, "[", "pred50") %>% unlist(),
                          under_50 = sapply(mis_class_ful_under, "[", "pred50") %>% unlist(),
                          over_50 = sapply(mis_class_ful_over, "[", "pred50") %>% unlist(),
                          full_80 = sapply(mis_class_ful, "[", "pred80") %>% unlist(),
                          sub_80 = sapply(mis_class_sub, "[", "pred80") %>% unlist(),
                          under_80 = sapply(mis_class_ful_under, "[", "pred80") %>% unlist(),
                          over_80 = sapply(mis_class_ful_over, "[", "pred80") %>% unlist()
                          )
rownames(rf_misclass) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5")

rf_misclass["avg",] <- colMeans(rf_misclass)

rf_misclass
```

```{r Point prediction 50}
point_miss50 <- lapply(list(full = rf_full_result, sub = rf_sub_result,
               under = rf_under_full_result, over = rf_over_full_result), function(result){
                 misclass_point <- extract_list_item(result, "mis_class_point") %>% 
                   extract_list_item("pred50") %>% unlist()
                 misclass_point <- c(misclass_point, mean(misclass_point))
                 names(misclass_point) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5", "Avg")
                 return(misclass_point)
})

point_miss50
```

```{r Point Missclass 8-}
point_miss80 <- lapply(list(full = rf_full_result, sub = rf_sub_result,
               under = rf_under_full_result, over = rf_over_full_result), function(result){
                 misclass_point <- extract_list_item(result, "mis_class_point") %>% 
                   extract_list_item("pred80") %>% unlist()
                 misclass_point <- c(misclass_point, mean(misclass_point))
                 names(misclass_point) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5", "Avg")
                 return(misclass_point)
})

point_miss80
```


```{r AUC}
# Obtain the AUC of the models
auc <- lapply(list(full = rf_full_result, sub = rf_sub_result,
               under = rf_under_full_result, over = rf_over_full_result), function(result){
                 auc <- extract_list_item(result, "auc") %>% unlist()
                 auc <- c(auc, mean(auc))
                 names(auc) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5", "Avg")
                 return(auc)
})

auc
```

```{r Interval Score 50}
# Calculate the interval score for 50% interval
is50 <- lapply(list(full = rf_full_result, sub = rf_sub_result,
               under = rf_under_full_result, over = rf_over_full_result), function(result){
                 is50 <- extract_list_item(result, "interval_score") %>%
                   extract_list_item("is50") %>% unlist()
                 is50 <- c(is50, mean(is50))
                 names(is50) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5", "Avg")
                 return(is50)
})
is50
```


```{r Interval Score 80}
# Calculate the interval score for 50% interval
is80 <- lapply(list(full = rf_full_result, sub = rf_sub_result,
               under = rf_under_full_result, over = rf_over_full_result), function(result){
                 is80 <- extract_list_item(result, "interval_score") %>%
                   extract_list_item("is80") %>% unlist()
                 is80 <- c(is80, mean(is80))
                 names(is80) <- c("Fold1", "Fold2", "Fold3", "Fold4", "Fold5", "Avg")
                 return(is80)
})
is80
```

## Save rf_model_realvant info
```{r}
save(rf_full_result, rf_under_full_result, rf_over_full_result,
     file = paste0(here::here(), "/Data/rf_model_objects.RData"))
```

```{r}
save(rf_misclass, auc, is50, is80, file = paste0(here::here(), "/Data/rf_results.RData"))
```



