---
title: "RFE_for_Random_Forest"
output: github_document  
author: Shuyi Tan  
editor_options: 
  chunk_output_type: inline
---

```{r Examine RFE results }
# source code to run recursive feature elimination for each training fold
# for (k in 1:5){
#   train_folds <- airbnb_data_sub[-folds[[k]], ]
#   res <- rfe_rf_procedure(train_folds)
#   save(res, file = paste0(here::here(), '/Data/rfe_',k, '.Rdata'))
# }

# Load the RFE results from each folds 
res_rfe_sub_1 <- loadRData(paste0(here::here(), '/Data/rfe_1.Rdata'))
res_rfe_sub_2 <- loadRData(paste0(here::here(), '/Data/rfe_2.Rdata'))
res_rfe_sub_3 <- loadRData(paste0(here::here(), '/Data/rfe_3.Rdata'))
res_rfe_sub_4 <- loadRData(paste0(here::here(), '/Data/rfe_4.Rdata'))
res_rfe_sub_5 <- loadRData(paste0(here::here(), '/Data/rfe_5.Rdata'))

# check what would be the best number of variables 
# by plot
plot(res_rfe_sub_1, type = c('g','o'), main="Fold 2-5")
plot(res_rfe_sub_2, type = c('g','o'), main="Fold 1 and 3-5")
plot(res_rfe_sub_3, type = c('g','o'), main="Fold 1-2 and 4-5")
plot(res_rfe_sub_4, type = c('g','o'), main="Fold 1-3 and 5")
plot(res_rfe_sub_5, type = c('g','o'), main="Fold 1-4")

# by number 
res_rfe_sub_1$bestSubset
res_rfe_sub_2$bestSubset
res_rfe_sub_3$bestSubset
res_rfe_sub_4$bestSubset
res_rfe_sub_5$bestSubset

```


```{r}
# Check the top varibles 
res_rfe_sub_1$optVariables[1:5]
res_rfe_sub_2$optVariables[1:5]
res_rfe_sub_3$optVariables[1:5]
res_rfe_sub_4$optVariables[1:5]
res_rfe_sub_5$optVariables[1:5]
```

